    language: python
    python:
      - "2.7"
    env:
      - DJANGO=1.11
    install:
      - pip install -r backend/pima/requirements.txt
    before_script:
      - cd backend/pima
      - python manage.py migrate
    script:
      - python manage.py test

    notifications:
      slack: kaweddemu:wPmFWij7VXKuAqhjDKbTs6TK