matrix:
  include:
    language: python
    python:
      - "2.7"
    env:
      - DJANGO=1.11
    install:
      - pip install -r backend/pima/requirements.txt
      - pip install coveralls
    before_script:
      - cd backend/pima
      - python manage.py migrate
    script:
      - coverage run --source='.' manage.py test --settings=pima.settings.test
    after_success:
      - coveralls
    deploy:
      skip_cleanup: true
      provider: script
      script: .travis/deploy.sh
      on:
        all_branches: true
  include:
    language: node_js
    node_js:
      - '5.0.0'
    install:
      - cd frontend
      - npm install
    script:
      - npm run test-coverage
      - npm run lint
notifications:
  slack: kaweddemu:wPmFWij7VXKuAqhjDKbTs6TK
