    language: python
    python:
      - "2.7"
    env:
      - DJANGO=1.11
    install:
      - pip install -r backend/pima/requirements.txt
      - pip install coveralls
    before_script:
      - cd backend/pima
      - python manage.py migrate
    script:
      - coverage run --'.' manage.py test
    after_success:
      - coveralls

    notifications:
      slack: kaweddemu:wPmFWij7VXKuAqhjDKbTs6TK