sudo: required
dist: trusty
language: node_js
node_js:
  - '5.0.0'
python:
  - "2.7"
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
before_install:
  - sudo apt-get update
#  - sudo apt-get -y install python-pip python-dev
#  - sudo pip install -U setuptools
#  - sudo pip install -U virtualenvwrapper
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose --version

install:
  - pip install -r backend/pima/requirements.txt
  - pip install coveralls
  - cd frontend
  - npm install
before_script:
  - cd ../backend/pima
  - docker-compose up
script:
  - coverage run --source='.' manage.py test --settings=pima.settings.test
  - cd ../../frontend/
  - npm run test-coverage
  - npm run lint
after_success:
  - coveralls
#deploy:
#  - bash .travis/deploy.sh

notifications:
  slack: kaweddemu:wPmFWij7VXKuAqhjDKbTs6TK
