    language: python
    python:
      - "2.7"
    env:
      - DJANGO=1.11
    install:
      - pip install -r requirements.txt
    before_script:
      - cd backend
      - python manage.py migrate
    script:
      - python manage.py test