sudo: required
dist: trusty
language: node_js
node_js:
  - '5.0.0'
python:
  - "2.7"
services:
  - postgresql
  - redis
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip python-dev
  - sudo pip install -U setuptools
  - sudo pip install -U virtualenvwrapper

install:
  - pip install -r backend/pima/requirements.txt
  - pip install coveralls
  - cd frontend
  - npm install
before_script:
  - cd ../backend/pima
  - psql -c 'create database test;' -U postgres
  - python manage.py migrate
script:
  - coverage run --source='.' manage.py test --settings=pima.settings.test
  - cd ../../frontend/
  - npm run test-coverage
  - npm run lint
after_success:
  - coveralls
#deploy:
#  - bash .travis/deploy.sh

notifications:
  slack: kaweddemu:wPmFWij7VXKuAqhjDKbTs6TK
