version: '2'
services:
  db:
    image: postgres:9.6.3
    container_name: postgres-1
  redis:
    image: redis:3.0.7
    container_name: redis-1
  web:
    build: .
    container_name: django-1
    command: >
              bash -c "chmod +x wait-for-it.sh; ./wait-for-it.sh db:5432 --
              python manage.py collectstatic --noinput &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/src
    expose:
      - "8000"
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.13.0
    container_name: nginx-1
#    ports:
#      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
